# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 402)
        MainWindow.setStyleSheet("* {\n"
"    font-family: \"Nirmala UI\";\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #888;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(0, 112, 82);\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-size: 14px;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(0, 112, 82);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 126, 90);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 3px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"\n"
"/* QTableWidget */\n"
"\n"
"QHeaderView::section {\n"
"    background: rgb(0, 112, 82);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QHeaderView::section:hover {\n"
"    background-color: rgb(0, 126, 90);\n"
" }\n"
"\n"
"QTableWidget {\n"
"     gridline-color: #888;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background: transparent;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.tabla_registro = QtWidgets.QTableWidget(self.tab)
        self.tabla_registro.setObjectName("tabla_registro")
        self.tabla_registro.setColumnCount(5)
        self.tabla_registro.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_registro.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_registro.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_registro.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_registro.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_registro.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_registro.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_registro.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_registro.setItem(1, 1, item)
        self.gridLayout.addWidget(self.tabla_registro, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(446, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.btn_eliminar = QtWidgets.QPushButton(self.tab)
        self.btn_eliminar.setMinimumSize(QtCore.QSize(150, 35))
        self.btn_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/basura.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_eliminar.setIcon(icon)
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.gridLayout.addWidget(self.btn_eliminar, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(157, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.titulo = QtWidgets.QLineEdit(self.tab_2)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titulo)
        self.autor = QtWidgets.QLineEdit(self.tab_2)
        self.autor.setAlignment(QtCore.Qt.AlignCenter)
        self.autor.setObjectName("autor")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.autor)
        self.editorial = QtWidgets.QLineEdit(self.tab_2)
        self.editorial.setAlignment(QtCore.Qt.AlignCenter)
        self.editorial.setObjectName("editorial")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editorial)
        self.isbn = QtWidgets.QLineEdit(self.tab_2)
        self.isbn.setAlignment(QtCore.Qt.AlignCenter)
        self.isbn.setObjectName("isbn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.isbn)
        self.precio = QtWidgets.QLineEdit(self.tab_2)
        self.precio.setAlignment(QtCore.Qt.AlignCenter)
        self.precio.setObjectName("precio")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.precio)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.gridLayout_2.addLayout(self.formLayout, 1, 1, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(73, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 1)
        self.btn_agregar = QtWidgets.QPushButton(self.tab_2)
        self.btn_agregar.setMinimumSize(QtCore.QSize(110, 35))
        self.btn_agregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icons/agregar-documento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_agregar.setIcon(icon1)
        self.btn_agregar.setObjectName("btn_agregar")
        self.gridLayout_2.addWidget(self.btn_agregar, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 2, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registro de libros"))
        item = self.tabla_registro.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tabla_registro.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tabla_registro.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Título"))
        item = self.tabla_registro.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Autor"))
        item = self.tabla_registro.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Editorial"))
        item = self.tabla_registro.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ISBN"))
        item = self.tabla_registro.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Precio"))
        __sortingEnabled = self.tabla_registro.isSortingEnabled()
        self.tabla_registro.setSortingEnabled(False)
        item = self.tabla_registro.item(1, 1)
        item.setText(_translate("MainWindow", "Hola Mundo"))
        self.tabla_registro.setSortingEnabled(__sortingEnabled)
        self.btn_eliminar.setText(_translate("MainWindow", " Eliminar Registro"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label.setText(_translate("MainWindow", "Título:"))
        self.label_2.setText(_translate("MainWindow", "Autor:"))
        self.label_3.setText(_translate("MainWindow", "Editorial:"))
        self.label_4.setText(_translate("MainWindow", "ISBN:"))
        self.label_5.setText(_translate("MainWindow", "Precio:"))
        self.btn_agregar.setText(_translate("MainWindow", " Registrar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
